sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6

before_install:
  - gem install bundler

before install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "pjhg410@gmail.com"
  - git config --global user.name "parkmuhyeun"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "atgfLNAsEuflFhnzkp7L9epB2Ga7LkytkV2GtcOrpcf5IizxkA+CNJa7ReoEcL/wosK8k9MwXZ+4QRrdwEnAY6SFy+A0GqopYdXj7+Swka3LGSFEgTNA+IJ/O9RSbKUMNH74MsmJkG70JoqffTZW6LM5wOItwgZKG3ZfNiCl9LnvSMT2L4bj+3g2ktHvc+1kPFh7Nj78lyRg5IfJNWbZWbRkGbLCk+mS7b3lK01bvCX7AIaMPopUy5nqZh8SUcUt8ZIRnLvH5pya1W9etexUKIW0Zi9zrhTiQYeuRzoAVsH9eY41JgfyH2URkGNaCw0sis3ibpGhkYiJqcl3eDVMhq7dBR32Bb4u0XWwSRx2go5rcMUGfHrLNNPzHfXrkL1Rg4T095mLjp9Cz72TRmVIH7qTgjzMP0k8aY/+3kN8ofqhK4yG5T1Caah+zJQLtYtBtJu4adOgB3xQGYEuxyiPebMIl4C0crGt+9xzUAtCkbxHuy7dxAFStW3YbwkPH53EuiE6x52V6Z11uL678N55kGsGdrDEJPG0aagn/OS09QC8fnutL3lKugh4brB/mUGsAPHlwoK75Y/Jt/W0EUHmaXCVrsneWQlvgjTuEKmzAGa7Cg6CwseMfO2yoDmrUxqiXQulMpzxm4fGqNsqxCb8aHbN79KYf6BwQb2jtR11Uzc="
branches:
  only:
    - master