sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "pjhg410@gmail.com"
  - git config --global user.name "parkmuhyeun"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "l3Qc8SWCaYVGMP2ZJihColpvOyCcwu3N0Fjlbo/xFzdZ7dtsbHYb4TXfK4XL4tIt5YTUwAl8A+WZvACyqSgBPl742/V/a24gX5j9jv5rgLAMEUhUCT+ufXM6r99gRGu17gOl0d4eA4A8kBjNIrdwgduKMDBHf
wZPkUyV03DuW3Cy5Zg7wpl5SWhC4nA7ACJP0MRGdaZO+bUsGz2weVzUUADemJ2/itLmy1ML0fqH8sV1yAU+8D0BtFbB4armyCJKb5khO114g7e+vManzM8H5jUhi8uLpMPiDloldpH+c5BGJCY3WK2hhfWHkzlXn4Sbz0fgy
ykPKKcOBU//itwVGgNDVcXK+HNXrxlIy4YJVtVSusrIljXk8sIFpmp9P5sShbEjdPeSuGCnDWXbThHXf79vE4KV3O2+roXmKpHt9VfYDStsR6L7AeroyZ9xgBuK3OyLKQncY2wPRCTQi0cMovMKZys9cpXiR5ikvKS3ISMCA
ZoBYKRQf8FPz9c2RJK7xdlm2w2LSkZSdknxBRuseRLzB7yCJqoTsR15+Fu6+ifqcsEeXYCmJJcmpzaMM79NBC60KUKfkskO0cZ4tOdwdRY9Mvk1aAcUCk0e5gzx/q5LzNKbzt0hV/R9nIs1Vl0wRok6t+gXNBnC+sSD0DTaV
D7GX4vZdZXndpqx7pfvpH8="
branches:
  only:
    - master